---
title: "Class R6 for the questionnaire"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
library(readxl)
library(dplyr)
library(purrr)

```

# r6_Questionnaire


A questionnaire is created a list of one or multiple [XlsForm](http://xlsform.org)

```{r function-r6_questionnaire}
#' questionnaire class is a class to load, check and manipulate one or more than one XLSForm 
#' @importFrom R6 R6Class
#' 
#' @export

questionnaire <- R6::R6Class(classname = "questionnaire",
                           public = list(
                           ),
                           private = list(
                             
                           )
)
```

```{r development-test}

```


```{r examples-r6_questionnaire}

```

```{r tests-r6_questionnaire}
# test_that("r6_questionnaire works", {
# 
#   
#   expect_true( inherits(ref, "R6") )
#   
# 
# 
# })
```


# Utils for questionnaires
    
```{r development-utils, eval = FALSE}




```


```{r function-utils_xlsform}

```
  
  
```{r tests-utils_xlsform}
# test_that("utils_xlsform works", {
#   
# 
# })
```
  

```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(
  flat_file = "dev/flat_r6_questionnaire.Rmd", 
  vignette_name = "Class R6 for the questionnaire"
  )
```

