# WARNING - Generated by {fusen} from /dev/flat_r6_questionnaire.Rmd: do not edit by hand

#' questionnaire class is a class to load, check and manipulate one or more than one XLSForm 
#' @importFrom R6 R6Class
#' 
#' @export

questionnaire <- R6::R6Class(classname = "questionnaire",
                           public = list(
                             #' @description 
                             #' read the xlsx for each sheet and return a named list
                             #' @param path path to the file with the full referential
                             #' 
                             #' @importFrom readxl excel_sheets read_xlsx
                             #' 
                             #' @return named list
                             initialize = function(path){
                               # Define path
                               self$path <- path
                               
                               # Get sheets of xlsx
                               sheets <- names_of_sheet(path)
                               
                               # Read the xlsx file 
                               data <- lapply(
                                 sheets, 
                                 function(x){
                                   read_xlsx(path = path, sheet = x)}) |>
                                      setNames(nm = sheets)
                              
                               self$data <- data
                             }
                           ),
                           private = list(
                             
                           )
)
